// ─────────────────────────────────────────────────────────────
// Mock produce listings — replace with real API fetch later.
// Fields match the backend privacy-safe PublicListing shape.
// imageUrls point to /public/images/assets/products/ folder.
// ─────────────────────────────────────────────────────────────

import { ProduceListing } from "@/types/marketplace";

export const MOCK_LISTINGS: ProduceListing[] = [
  {
    id: "1",
    produceName: "Tomatoes",
    variety: "Sukari F1",
    categoryName: "Vegetables",
    sellerDisplayName: "Kirinyaga Farmers Cooperative",
    sellerVerified: true,
    region: "Kirinyaga District",
    harvestDate: "2026-09-01",
    expiryDate: null,
    totalQuantity: 2000,
    availableQuantity: 1500,
    unit: "KG",
    minimumOrderQty: 50,
    unitPrice: 45,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 80,
    imageUrls: ["/images/assets/products/tomatoes.jpg"],
    isOrganic: false,
    status: "PARTIALLY_SOLD",
  },
  {
    id: "2",
    produceName: "Irish Potatoes",
    variety: "Kinigi",
    categoryName: "Tubers",
    sellerDisplayName: "Musanze Highland Farmers",
    sellerVerified: true,
    region: "Musanze District",
    harvestDate: "2026-08-28",
    expiryDate: null,
    totalQuantity: 10000,
    availableQuantity: 10000,
    unit: "KG",
    minimumOrderQty: 100,
    unitPrice: 38,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 60,
    imageUrls: ["/images/assets/products/irish-potatoes.jpg"],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "3",
    produceName: "Cabbage",
    variety: "Gloria F1",
    categoryName: "Vegetables",
    sellerDisplayName: "Nyabihu Farmers Cooperative",
    sellerVerified: true,
    region: "Nyabihu District",
    harvestDate: "2026-09-02",
    expiryDate: null,
    totalQuantity: 5000,
    availableQuantity: 5000,
    unit: "KG",
    minimumOrderQty: 50,
    unitPrice: 25,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 70,
    imageUrls: ["/images/assets/products/cabbage.jpg"],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "4",
    produceName: "Peppers",
    variety: "California Wonder",
    categoryName: "Vegetables",
    sellerDisplayName: "Musanze Vegetable Growers",
    sellerVerified: true,
    region: "Musanze District",
    harvestDate: "2026-09-04",
    expiryDate: null,
    totalQuantity: 800,
    availableQuantity: 800,
    unit: "KG",
    minimumOrderQty: 20,
    unitPrice: 120,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: null,
    imageUrls: ["/images/assets/products/peppers.jpg"],
    isOrganic: true,
    status: "ACTIVE",
  },
  {
    id: "5",
    produceName: "Green Bananas",
    variety: null,
    categoryName: "Fruits",
    sellerDisplayName: "Eastern Province Agri-Coop",
    sellerVerified: true,
    region: "Eastern Province",
    harvestDate: "2026-09-01",
    expiryDate: null,
    totalQuantity: 2000,
    availableQuantity: 2000,
    unit: "KG",
    minimumOrderQty: 100,
    unitPrice: 35,
    currency: "KES",
    deliveryOptions: ["DELIVERED"],
    deliveryRadiusKm: 150,
    imageUrls: ["/images/assets/products/green-bananas.jpg"],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "6",
    produceName: "African Eggplant",
    variety: null,
    categoryName: "Vegetables",
    sellerDisplayName: "Bugesera Women Farmers Coop",
    sellerVerified: true,
    region: "Bugesera District",
    harvestDate: "2026-09-05",
    expiryDate: null,
    totalQuantity: 300,
    availableQuantity: 300,
    unit: "KG",
    minimumOrderQty: 10,
    unitPrice: 90,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP"],
    deliveryRadiusKm: null,
    imageUrls: ["/images/assets/products/eggplant.jpg"],
    isOrganic: true,
    status: "ACTIVE",
  },
];

export const CROP_CATEGORIES = [
  ...new Set(MOCK_LISTINGS.map((l) => l.categoryName)),
].sort();

export const LOCATIONS = [
  ...new Set(MOCK_LISTINGS.map((l) => l.region.replace(" District", "").replace(" Province", ""))),
].sort();
