// ─────────────────────────────────────────────────────────────
// Mock produce listings — replace with real API fetch later
// ─────────────────────────────────────────────────────────────

import { ProduceListing } from "@/types/marketplace";

export const MOCK_LISTINGS: ProduceListing[] = [
  {
    id: "1",
    produceName: "Tomatoes",
    variety: "Sukari F1",
    categoryName: "Vegetables",
    sellerName: "Kirinyaga Farmers Cooperative",
    sellerVerified: true,
    farmLocation: "Kirinyaga, Kenya",
    harvestDate: "2026-09-01",
    totalQuantity: 2000,
    availableQuantity: 1500,
    unit: "KG",
    minimumOrderQty: 50,
    unitPrice: 45,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 80,
    imageUrls: [],
    isOrganic: false,
    status: "PARTIALLY_SOLD",
  },
  {
    id: "2",
    produceName: "Rice",
    variety: "Basmati",
    categoryName: "Grains",
    sellerName: "Mwea Rice Growers Co-op",
    sellerVerified: true,
    farmLocation: "Mwea, Kenya",
    harvestDate: "2026-08-20",
    totalQuantity: 5000,
    availableQuantity: 5000,
    unit: "KG",
    minimumOrderQty: 100,
    unitPrice: 120,
    currency: "KES",
    deliveryOptions: ["DELIVERED"],
    deliveryRadiusKm: 150,
    imageUrls: [],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "3",
    produceName: "Irish Potatoes",
    variety: "Shangi",
    categoryName: "Tubers",
    sellerName: "Nyandarua Highland Farmers",
    sellerVerified: true,
    farmLocation: "Nyandarua, Kenya",
    harvestDate: "2026-09-03",
    totalQuantity: 3000,
    availableQuantity: 800,
    unit: "KG",
    minimumOrderQty: 100,
    unitPrice: 38,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 60,
    imageUrls: [],
    isOrganic: true,
    status: "PARTIALLY_SOLD",
  },
  {
    id: "4",
    produceName: "Maize",
    variety: "DK8031",
    categoryName: "Grains",
    sellerName: "Rift Valley Grain Cooperative",
    sellerVerified: false,
    farmLocation: "Nakuru, Kenya",
    harvestDate: "2026-08-15",
    totalQuantity: 10000,
    availableQuantity: 10000,
    unit: "KG",
    minimumOrderQty: 500,
    unitPrice: 28,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP"],
    deliveryRadiusKm: null,
    imageUrls: [],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "5",
    produceName: "Onions",
    variety: "Red Creole",
    categoryName: "Vegetables",
    sellerName: "Kajiado Small Farmers Union",
    sellerVerified: true,
    farmLocation: "Kajiado, Kenya",
    harvestDate: "2026-09-05",
    totalQuantity: 1500,
    availableQuantity: 1200,
    unit: "KG",
    minimumOrderQty: 50,
    unitPrice: 55,
    currency: "KES",
    deliveryOptions: ["SELF_PICKUP", "DELIVERED"],
    deliveryRadiusKm: 50,
    imageUrls: [],
    isOrganic: false,
    status: "ACTIVE",
  },
  {
    id: "6",
    produceName: "Spinach",
    variety: null,
    categoryName: "Vegetables",
    sellerName: "Kiambu Organic Growers",
    sellerVerified: true,
    farmLocation: "Kiambu, Kenya",
    harvestDate: "2026-09-07",
    totalQuantity: 500,
    availableQuantity: 500,
    unit: "KG",
    minimumOrderQty: 20,
    unitPrice: 80,
    currency: "KES",
    deliveryOptions: ["DELIVERED"],
    deliveryRadiusKm: 40,
    imageUrls: [],
    isOrganic: true,
    status: "ACTIVE",
  },
];

export const CROP_CATEGORIES = [
  ...new Set(MOCK_LISTINGS.map((l) => l.categoryName)),
].sort();

export const LOCATIONS = [
  ...new Set(
    MOCK_LISTINGS.map((l) => l.farmLocation.split(",")[0].trim())
  ),
].sort();
